spring:
  profiles:
    #更换环境,引入使用application-local.xml
    active: local
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#变量配置，可以通过代码访问
demo:
  name: chengxulaoren
  age: 100


